# This setup file usually already contained in the dataset.zip with the name 'data.yaml' so u can just rename the file into 'test-config.yaml'

path: "/content/gdrive/MyDrive/Eco Report/Datasets"
train: /train/images
val: /valid/images
test: /test/images

nc: 6
names: ['0', 'c', 'garbage', 'garbage_bag', 'sampah-detection', 'trash']

roboflow:
  workspace: tcs-e77d0
  project: aggra
  version: 2
  license: CC BY 4.0
  url: https://universe.roboflow.com/tcs-e77d0/aggra/dataset/2
